{
 "title": "ClickHouse - Charging Station",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Orders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(idTag) orders FROM iot_data.\"charging_order\" WHERE   ( endTimestamp  >= $__fromTime AND endTimestamp <= $__toTime ) LIMIT 100"
    }
   ]
  },
  {
   "title": "Business Revenue",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "￥" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(CASE WHEN toHour(timestamp) >= 0 AND toHour(timestamp) < 8 THEN power * 1.2\n           ELSE 0\n      END) AS \"00:00-08:00\",\n  SUM(CASE WHEN toHour(timestamp) >= 8 AND toHour(timestamp) < 24 THEN power * 1.6\n           ELSE 0\n      END) AS \"08:00-24:00\"\nFROM iot_data.\"charging_record\"\n  WHERE ( timestamp  >= $__fromTime AND timestamp <= $__toTime )\n"
    }
   ]
  },
  {
   "title": "Average Electricity per order",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(meter) avgElectricity FROM iot_data.\"charging_order\" WHERE   ( endTimestamp  >= $__fromTime AND endTimestamp <= $__toTime ) LIMIT 100"
    }
   ]
  },
  {
   "title": "Duration per order",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(duration) FROM iot_data.\"charging_order\" WHERE   ( endTimestamp  >= $__fromTime AND endTimestamp <= $__toTime ) LIMIT 100"
    }
   ]
  },
  {
   "title": "Total Electricity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(meter) meter FROM iot_data.\"charging_order\" WHERE   ( endTimestamp  >= $__fromTime AND endTimestamp <= $__toTime ) LIMIT 100"
    }
   ]
  },
  {
   "title": "Electricity per charging nozzle",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT idTag, sum(meter) FROM iot_data.\"charging_order\" WHERE   ( endTimestamp  >= $__fromTime AND endTimestamp <= $__toTime ) GROUP BY idTag ORDER BY idTag ASC LIMIT 100"
    }
   ]
  },
  {
   "title": "Disconnect Reason",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT stopReason, count(*) count FROM iot_data.\"charging_order\" WHERE   ( endTimestamp  >= $__fromTime AND endTimestamp <= $__toTime ) GROUP BY stopReason LIMIT 100"
    }
   ]
  },
  {
   "title": "Charging station Utilization Rate",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT\n    idTag,\n    SUM(duration) / (toUnixTimestamp($__toTime) - toUnixTimestamp($__fromTime)) AS idleRate\nFROM  iot_data.\"charging_order\"\nWHERE ( $__fromTime >= startTimestamp  AND $__toTime  <= endTimestamp )\nGROUP BY idTag\norder by idTag asc\nlimit 100\n"
    }
   ]
  },
  {
   "title": "Hourly Electricity",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfHour(timestamp) AS hour,\n    SUM(power) AS totalPower\nFROM\n    charging_record\nWHERE\n    hour >= toDate(timestamp) AND hour < addDays(toDate(timestamp), 1) and  toHour(timestamp) >= 8\n    \nGROUP BY\n    hour\nORDER BY\n    hour;\n"
    }
   ]
  }
 ]
}